// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WIB.Infrastructure.Data;

#nullable disable

namespace WIB.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WibDbContext))]
    [Migration("20251004211000_AddStoreDetails")]
    partial class AddStoreDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WIB.Domain.Store", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Address")
                    .HasColumnType("text");

                b.Property<string>("Chain")
                    .HasColumnType("text");

                b.Property<string>("City")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PostalCode")
                    .HasColumnType("text");

                b.Property<string>("VatNumber")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Stores");
            });
        }
    }
}

